config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, presence:true, acceptance: { accept: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { :in => 0..5 }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "new"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

 private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant %></li>
<% end %>
</ul>

<%= link_to 'Add new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<% if @restaurant.reviews.empty? %>
  <p><i>No reviews for this restaurant</i></p>
<% else %>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.content %>
        <%= review.rating %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>